name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Grazie per aver segnalato qualcosa da sistemare! Aspettiamo un tuo contributo :-)"
        pr-message: "Grazie per aver contributo al progetto !"
